# Generated by Django 3.2.11 on 2022-02-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf_app', '0002_article_author_tag_track'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='author',
            name='mobile',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='author',
            name='salary',
            field=models.FloatField(blank=True, null=True, verbose_name='Salary'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='tag_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='track',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address'),
        ),
    ]
