# Generated by Django 3.2.11 on 2022-02-17 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf_app', '0003_auto_20220217_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='article',
            name='document',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='document'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='image'),
        ),
        migrations.AlterField(
            model_name='article',
            name='num_stars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_date',
            field=models.DateField(blank=True, null=True, verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='article',
            name='publish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Publish Time'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
