# Generated by Django 3.2.11 on 2022-02-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf_app', '0004_auto_20220217_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(null=True, to='psf_app.Tag'),
        ),
        migrations.AlterField(
            model_name='article',
            name='youtube_link',
            field=models.URLField(blank=True, max_length=255, null=True, verbose_name='Youtube Link'),
        ),
    ]
