# Generated by Django 3.2.11 on 2022-02-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psf_app', '0005_auto_20220217_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(blank=True, to='psf_app.Tag'),
        ),
    ]
